name: Deployment live

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Composer Install
        run: composer install --no-scripts --no-dev --no-progress --no-interaction --prefer-dist --optimize-autoloader
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GH_TOKEN }}"}}'

      - name: NodeJS Installation
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: NPM Installation & Build
        run: |
          npm i -g npm@10
          npm ci --include=optional
          npm run fonts
          npm run images
          npm run favicons
          npm run build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create SSH directory and add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync with password authentication (safe mode, no delete)
        run: |
          sshpass -p "${{ secrets.REMOTE_PASSWORD }}" rsync -az \
            -e "ssh -p ${{ secrets.REMOTE_PORT }}" \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude 'site/languages' \
            --exclude 'public/.htaccess' \
            --exclude 'public/robots.txt' \
            ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:public_html/live
